config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "/" => "main#index"

  get "/users" => "users#index"
  get "/users/current" => "users#show"
  post "/users" => "users#create"
  put "/users/current" => "users#update"

  get "/plants" => "plants#index"
  get "/plants/:id" => "plants#show"
  post "/plants" => "plants#create"
  patch "/plants/:id" => "plants#update"
  delete "/plants/:id" => "plants#delete"

  get "/schedules" => "schedules#index"
  get "/schedules/plant/:id" => "schedules#show_of_plant"
  get "/schedules/:id" => "schedules#show"
  post "/schedules" => "schedules#create"
  put "/schedules" => "schedules#update"
  put "schedules/:id/water" => "schedules#water"
  delete "/schedules/:id" => "schedules#delete"
  patch "/reset" => "schedules#reset"

  get "/plant_counts" => "plant_counts#index"
  put "/plant_counts/all" => "plant_counts#update_all"
  put "/plant_counts" => "plant_counts#update"
  post "/plant_counts" => "plant_counts#create"

  post "/sessions" => "sessions#create"

  post "/test" => "plant_counts#create"
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :schedules
  has_many :plant_counts
end

app/controllers/plants_controller.rb
# days_to_water is a static number that represents the time gap between needing to water a specific plant
# growth_req is a static number that represents the base amount of times you need to water the plant until it is fully grown

class PlantsController < ApplicationController
  def index
    @plants = Plant.all
    render :index
  end
  def show
    @plant = Plant.find_by(id: params[:id])
    render :show
  end
  def create
    @plant = Plant.create(
      name: params[:name],
      description: params[:description],
      amount_of_sun: params[:amount_of_sun],
      days_to_water: params[:days_to_water],
      growth_req: params[:growth_req]
    )
  end
  def update
    @plant = Plant.find_by(id: params[:id])
    @plant.update(
      name: params[:name] || @plant.name,
      description: params[:description] || @plant.description,
      amount_of_sun: params[:amount_of_sun] || @plant.amount_of_sun,
      days_to_water: params[:days_to_water] || @plant.days_to_water,
      growth_req: params[:growth_req] || @plant.growth_req
    )
    render :show
  end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
</div>

app/views/plants/edit.html.erb
<% content_for :title, "Editing plant" %>

<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant %> |
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Plants" %>

<h1>Plants</h1>

<div id="plants">
  <% @plants.each do |plant| %>
    <%= render plant %>
    <p>
      <%= link_to "Show this plant", plant %>
    </p>
  <% end %>
</div>

<%= link_to "New plant", new_plant_path %>

app/views/plants/new.html.erb
<% content_for :title, "New plant" %>

<h1>New plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plant %>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant) %> |
  <%= link_to "Back to plants", plants_path %>

  <%= button_to "Destroy this plant", @plant, method: :delete %>
</div>